# Generated by Django 4.1.3 on 2022-12-05 15:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0010_remove_comment_id_alter_comment_pedido"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reply",
            fields=[
                (
                    "comment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="comments",
                        serialize=False,
                        to="user.comment",
                    ),
                ),
                ("text", models.CharField(max_length=255)),
                ("datetime", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name="comment",
            name="pedido",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                related_name="comments",
                serialize=False,
                to="user.pedido",
            ),
        ),
        migrations.AlterField(
            model_name="pedido",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pedidos",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
