# Generated by Django 4.1.3 on 2022-11-26 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.IntegerField(default=0)),
                ('tel', models.IntegerField(default=0)),
                ('city', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logoURL', models.URLField(blank=True, max_length=300, null=True)),
                ('cnpj', models.IntegerField(default=0)),
                ('tel', models.IntegerField(default=0)),
                ('job', models.CharField(default='Municipal', max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('score', models.IntegerField(default=0)),
            ],
        ),
    ]
