# Generated by Django 4.1.3 on 2022-11-26 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Client",
        ),
        migrations.DeleteModel(
            name="Company",
        ),
    ]
