# Generated by Django 4.1.2 on 2022-11-25 14:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameField(
            model_name='company',
            old_name='name',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='text',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='likes',
            new_name='rating',
        ),
        migrations.RemoveField(
            model_name='company',
            name='poster_url',
        ),
        migrations.RemoveField(
            model_name='company',
            name='release_year',
        ),
        migrations.RemoveField(
            model_name='review',
            name='author',
        ),
        migrations.RemoveField(
            model_name='review',
            name='company',
        ),
        migrations.AddField(
            model_name='company',
            name='cnpj',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='company',
            name='job',
            field=models.CharField(default='Municipal', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='tel',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.company')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.IntegerField(default=0)),
                ('tel', models.IntegerField(default=0)),
                ('city', models.CharField(max_length=255)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.user')),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.user')),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='user_id',
            field=models.ForeignKey(default=00000, on_delete=django.db.models.deletion.CASCADE, to='companies.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='request_id',
            field=models.ForeignKey(default=00000, on_delete=django.db.models.deletion.CASCADE, to='companies.request'),
            preserve_default=False,
        ),
    ]
