# Generated by Django 4.1.2 on 2022-11-25 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_user_rename_name_company_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='job',
            field=models.CharField(default='Municipal', max_length=255),
        ),
        migrations.AlterField(
            model_name='company',
            name='user_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='companies.user'),
        ),
        migrations.AlterField(
            model_name='review',
            name='request_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='companies.request'),
        ),
    ]
