# Generated by Django 4.1.3 on 2022-11-25 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_company_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='logoURL',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
    ]
