# Generated by Django 4.1.3 on 2022-12-02 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0008_alter_pedido_company"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="body",
            new_name="review",
        ),
    ]
